version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - local
      - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    env_file:
      - .env
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    depends_on:
      - web
    profiles:
      - ngrok
