blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/bichitra07/ugc_net_answerkey_checker/discussions
    about: "If you have questions, you can ask them in Discussions."
