# .github/workflows/release.yml

name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags that start with 'v' followed by digits (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and Package
      run: |
        # Add build and package commands here
        echo "Building and packaging the project..."

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automated release for ${{ github.ref }}
        draft: false
        prerelease: false
